version: '3.4'

services:
  militarymanager:
    image: ${DOCKER_REGISTRY-}militarymanager
    build:
      context: .
      dockerfile: MilitaryManager/Dockerfile

  militarymanager.attachments.api:
    image: ${DOCKER_REGISTRY-}militarymanagerattachmentsapi
    build:
      context: .
      dockerfile: MilitaryManager.Attachments.API/Dockerfile

  militarymanager.units.api:
    image: ${DOCKER_REGISTRY-}militarymanagerunitsapi
    build:
      context: .
      dockerfile: MilitaryManager.Units.API/Dockerfile

  militarymanager.identity.server:
    image: ${DOCKER_REGISTRY-}militarymanager_identity_server
    build:
      context: .
      dockerfile: MilitaryManager.IdentityServer/Dockerfile

  azure-blob-storage:
   image: mcr.microsoft.com/azure-blob-storage:latest
   hostname: azure-blob-storage
   environment:
      LOCAL_STORAGE_ACCOUNT_NAME: militarymanager
      LOCAL_STORAGE_ACCOUNT_KEY: C/yu8u+EAak7iTH73rUCUj+2NZr6NNgFRPtFPGnJtPYvpZfaW9QJopXd/Xh0HrmzakkWyw/28hss+AStsgfKVg==   
   volumes:
       - "blobdata:/data"
   ports:
      - 11002:11002

volumes:
    blobdata:
        external: false