version: '3.4'

services:
  militarymanager:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
 
  militarymanager.attachments.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - identityUrl=http://militarymanager.identity.server
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=MilitaryManager_Attachments;User ID=alex;Password=P@ssw0rd;MultipleActiveResultSets=true;Application Name=Attachments
    ports:
      - "5002:80"
      - "5003:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  militarymanager.units.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - identityUrl=http://militarymanager.identity.server
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=Units;User ID=alex;Password=P@ssw0rd;MultipleActiveResultSets=true;Application Name=MilitaryManager.Units.API
    ports:
      - "5004:80"
      - "5005:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  militarymanager.identity.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=IdentityServer_AspNet_Identity;User ID=alex;Password=P@ssw0rd;MultipleActiveResultSets=true;Application Name=IdentityServer
    ports:
      - "5006:80"
      - "5007:443"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  azure-blob-storage:
   image: mcr.microsoft.com/azure-blob-storage:latest
   hostname: azure-blob-storage
   environment:
      LOCAL_STORAGE_ACCOUNT_NAME: militarymanager
      LOCAL_STORAGE_ACCOUNT_KEY: C/yu8u+EAak7iTH73rUCUj+2NZr6NNgFRPtFPGnJtPYvpZfaW9QJopXd/Xh0HrmzakkWyw/28hss+AStsgfKVg==   
   volumes:
       - "blobdata:/data"
   ports:
     - 11002:11002

volumes:
    blobdata:
        external: false